### ISSUE TITLE
How to maintain react state instead of props in react?

### ISSUE THREAD

**Issue by cloudybrain** [davidchang/ngReact#102]
I have something that looks like this:

    <react-component name="example" framesize="FrameSizeData" />

However I'd like to configure changes, so that when new data is changed, the component would be re-rendered to reflect the changes

    var example = React.createClass({
        getInitialState:  function () {
            return {
                test = ""
            }
        },
    },
    handleClick: function () {
        this.setState({
            test : "test1"
        });
    },
    render: function() {
        return (
            <div>
                <input type="text" ref="myTextInput" value="this.state.test" />
                <input
                    type="button"
                    value="Focus the text input"
                    onClick={this.handleClick}
             />
          </div>
        );
    }});

The only way I was able to do this was create my own global variables, and pass in data from the controller, and when it builds the react component, it will take that global variable. But I'd rather have a way to pass in $scope instead.

**Comment by cloudybrain** [comment]
To elaborate more, I have react components that depend on each other, so it's sibling to sibling communication, so when one react component changes, it effects data in another react component.

Like lets say, I have two dropdown boxes, both dropdown boxes retrieve data using ajax to populate the component when the page loads. When the first dropdown changes, the second dropdown uses the first dropdown in its new query using ajax to retrieve a different set of data. So we're talking about cascading dropdowns, which react can't do by itself. Angular has this ability if you just create a directive and just force them to depend on each other.

I'd like angular to handle all the data within the $scope on the controller side, if there's a way to send the $scope to a react component, and "watch" these changes, have it automatically re-render. So far, all my react component using ngReact are built by having angular send data to the component on page load, and that's all it does.

**Comment by cloudybrain** [comment]
I'm thinking this isn't supported the way it is now, maybe move this to a feature request? I was able to change the cascading dropdown design into a different work flow using a filterable table - which the clients seem to like really well.

**Comment by kasperp** [comment]
@cloudybrain thanks for you question. The way to communicate state changes from a component "back" to angular is through a callback, see #43. There is also a discussion about it [here](https://github.com/davidchang/ngReact/pull/11#issuecomment-60485903).

> I'd like angular to handle all the data within the $scope on the controller side, if there's a way to send the $scope to a react component, and "watch" these changes, have it automatically re-render.

I think this a good approach and I think it is one that works very well with ngReact. You pass down data from angular to the react component via props, you also pass down callbacks for updating this data. This way when you change the data (by calling callback from a React component) ngReact will rerender the react components with the changed props. 

Let me know if I have misunderstood your scenario :smile:

**Comment by cloudybrain** [comment]
ahh perfect, I didn't realize there were callbacks to angular, that is what I needed. In fact, I think this is way better than letting react handle the state of the data, having angular take care of it for react is so much more convenient and it makes much more sense. I love this library you got here! I've been recommending it throughout my company.
