### ISSUE TITLE
recursive $digest() iterations using ng-react

### ISSUE THREAD

**Issue by De-Lac** [davidchang/ngReact#104]
I am trying to use ngReact instead of ngRepeat to improve performance when I modify my $watched array of objects. 

For each object (a map marker) contained in the controller, I want to create a `<button>`, with the `marker.title` as text. For this purpose, I crated a React `<div>` component that $watches an array of markers. Such a `<div>` contains a list of `<button>`, one for each marker. I supposed that the component will result _changed_ (and then updated) only if I modify the list of markers.

However this is not the case. The rendered component results always a different instance, recursively calling the $digest() cycle rising the error:

```
    [TypeError]: Illegal invocation
      at isArrayLike (angular.js:274)
      at forEach (angular.js:328)
      at copy (angular.js:886)

    [Error]: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
    Watchers fired in the last 5 iterations: []
    http://errors.angularjs.org/1.4.0-rc.0/$rootScope/infdig?p0=10&p1=%5B%5D
        at REGEX_STRING_REGEXP (angular.js:68)
        at Scope.parent.$get.Scope.$digest (angular.js:15340)
        at Scope.parent.$get.Scope.$apply (angular.js:15570)
        at (index):95
```

It seems that the list of the `<button>` created by the React component results always different, even if made by the same objects.

Here it is my React component (at the end of my post, there is the JSfiddle link)

HTML
```html
        <!-- m_list is an attribute of $rootScope -->
        <poi-list list="m_list" />
```

JS
```javascript
    .value( "PoiList", React.createClass( {
    
      propTypes : {
    
        list: React.PropTypes.object.isRequired
      },
    
      render: function() 
       {
        var markers = this.props.list.map( function( marker, i ) 
            {//for each marker, create a button
             return React.DOM.button(  {
                                        className:'btn btn-default'                               
                                       }, marker.title
                                     ) ; 
            } );
        return React.DOM.div({}, markers);
        }
    
    
    }))
    
    .directive( 'poiList', function( reactDirective ) {
      return reactDirective( 'PoiList' );
    } );
```

[this is a JSFiddle][1] of my problem. A brief description:

- there are 2 arrays in the $rootScope. temp_list is used to temporarily push all the markers one by one. m_list is $watched by the react component.
- there is a MapBox directive with its controller. For each marker added to the map, it will be pushed in the temp_list.
- once all the markers have been loaded and temp_list is complete, this is cloned to m_list, so the react component can be updated.

 
thank you

  [1]: https://jsfiddle.net/xg0Ln79q/1/

**Comment by puopg** [comment]
I am also experiencing the same thing. Any updates?

**Comment by kasperp** [comment]
@De-Lac thanks for reporting this. It looks like you're correct. If you have any ideas for a fix/workaround please share.

**Comment by De-Lac** [comment]
Actually yes,  I found a solution just in these days, after a month! The problem somehow is connected to the use of the map. In the watched array, I am not adding the Json markers, but I am adding the object marker created by MapBox.
```javascript
map.featureLayer.setGeoJSON(json_markers_list);  // I pass an array of Json markers
map.featureLayer.on('layeradd', function(e) 
				{
			         var marker = e.layer;        // marker is anymore a json obj
			         ctrl.pushMarker(marker);  // marker now has a cyclic structure
			        });
```
The object marker created by MapBox, has a cyclic structure. For this reason, React cannot know if the old $watched array has changed since the last check, because it cannot perform isArrayLike when cycle structure is present. So it rises an error (different from any browser) and considers the array always changed, generating the $digest infinite iteration.

My solution is using one array and one map. The array is $watched with just the information I need to display in the button
```javascript 
{'title': 'marker title', 'id':00001}
```
the map contains the real marker objects
{'00001' : {markerObj}}

**Comment by De-Lac** [comment]
and this is a working [JSFiddle](https://jsfiddle.net/o43e0nqp/1/) !

**Comment by kasperp** [comment]
So this wasn't a ngReact issue ?

**Comment by De-Lac** [comment]
Well.... now I know that React can't perform the check with arrays that have cycle structure. I don't know if it's a real problem of ngReact, or it works as supposed to do
