### ISSUE TITLE
Compatibility with React 0.14.x

### ISSUE THREAD

**Issue by justVitalius** [davidchang/ngReact#112]
How soon will have a new release version with support for react 0.14.x?

**Comment by aabenoja** [comment]
#110 #111

**Comment by aabenoja** [comment]
#109

**Comment by kasperp** [comment]
Now - https://github.com/davidchang/ngReact/releases/tag/0.2.0

**Comment by justVitalius** [comment]
You are awesome!

**Comment by mikeerickson** [comment]
@kasperp perfect timing!  I just came here to see if ngReact was ready for 0.14 and I see this :-)

Thanks!
