### ISSUE TITLE
Bower.json not updated.

### ISSUE THREAD

**Issue by kingshukb** [davidchang/ngReact#117]
Hi guys,
I find that the package.json file has updated version of react(0.14) and a new dependency of react-dom(0.14.0), but the bower.json is having onlu dependancy of react(0.12.0).

So kindly update the bower.json to the latest version of react.

Thanks.

**Comment by kasperp** [comment]
Thanks for reporting this. I update the bower.json file in 7911eeb0c6d690d51f550d969b2aedf0dfe8295c, feel free to reopen this issues if there are other problems.
