### ISSUE TITLE
reactComponent and controllerAs

### ISSUE THREAD

**Issue by jasedwards** [davidchang/ngReact#40]
the react component does not work with controllerAs structure. The reason being if you have this in your html: props="home.config" then reactComponent does this scope[attrs.props] which comes back as undefined.  Are there any plans to support controllerAs or are you aware of a work around?

**Comment by kasperp** [comment]
@jasedwards thanks for reporting this. I will look into this, if you would like to speed up the process you could provide an example that illustrates the issue.

**Comment by jasedwards** [comment]
I will work on an example for you.  In the mean time I created something called reactComponentAs which is identical to reactComponent but instead of scope[attrs.props] I did scope.$eval(attrs.props).  Worked for my case but have not had a chance to fully test it yet.

**Comment by kasperp** [comment]
@jasedwards I think your suggested fix is correct. In fact we do the same thing in the reactDirective service when evaluating attributes. 

I have added a pull request with the fix and an example that uses controllerAs. Does that solve your issue ?

**Comment by jasedwards** [comment]
that fixes it.  Thanks
