### ISSUE TITLE
Can I use ng-react with ng-route?

### ISSUE THREAD

**Issue by rageofaxe** [davidchang/ngReact#42]
Maybe, I'm doing something wrong, but i catch error "Cannot find react component"

**Comment by kasperp** [comment]
@rageofaxe thanks for the issue ?, could you provide an example or more information.

**Comment by hasdavidc** [comment]
@rageofaxe I'm not aware of any conflict between the two (ng-react really just adds services and directives, doesn't touch anything to do with routing). If you can provide an example, we could help identify what's going on
