### ISSUE TITLE
Is this still being developed?

### ISSUE THREAD

**Issue by chino23** [davidchang/ngReact#44]
Hi,

I'm really intrigued about using React with AngularJS. This project hasn't seen activity in over a month, is this still being developed? I'd love to see this project go on.

Thanks!

**Comment by kasperp** [comment]
@chino23 the project is active, we haven't done any new development for a while. Are there any new functionality you would like to see ?

**Comment by chino23** [comment]
Thanks for the quick reply. Nothing in particular as I'm just about to jump in, just wanted to make sure this has not been abandoned yet :)

**Comment by kasperp** [comment]
nope not yet :wink:

**Comment by chino23** [comment]
Happy to hear that :)
