### ISSUE TITLE
Option in directive for watch / watchCollection / deep watch comparison

### ISSUE THREAD

**Issue by djett41** [davidchang/ngReact#47]
By default the ngReact directives use deep watch comparison which can be pretty expensive and/or unnecessary depending on your data.  

What do you think about adding a watchType or something similar that would allow us to define how to watch the incoming react data?  Just a thought.

Also, not sure if you need another issue for this, but the replace property for directives has been deprecated, although one could argue that the next major release, 2.0, will be so different that it may not even be a big deal or a deal at all lol!

**Comment by kasperp** [comment]
@djett41 Thanks for the contributing. I think it sounds like a good idea to make it possible to change how the properties are watched. Have you encountered any concrete perf. problems ?

Would you like to do a pull request or wait for me to get around to adding it in ?

> but the replace property for directives has been deprecated, will be so different that it may not even be a big deal or a deal at all

I wasn't aware of this no. I'm not sure what todo about it, do you think we should remove the `replace` flag from the directive ?

@davidchang any thoughts.

**Comment by djett41** [comment]
@davidchang No problem!  

As far as the replace flag, I think we could remove it.  This would mean that in the DOM you would see the actual angular directive and then the react components html nested, but I don't think that makes any difference.  Besides you can just look at it as another component ;-)

I haven't run into any performance issues, however in my use case I have a collection of objects that can also have collections (although they dont need to be watched), so deep watching this collection would add some unnecessary watchers.  Don't think it would be a huge difference but still any little performance boost will help, especially when running on a mobile device ;-)

I can get to both this weekend!

Thanks

**Comment by kasperp** [comment]
cool, 

About removing `replace`: after skimming through the comments on the [commit](https://github.com/angular/angular.js/commit/eec6394a342fb92fba5270eee11c83f1d895e9fb) that deprecated it, I'm not convinced that removing it is the right thing for now. 

If you use the `reactDirective` service to generate named directives for your components you can override the configuration of the generated directive like this:

```javascript
app.directive('hello', function(reactDirective) {
  return reactDirective(HelloComponent, undefined, {replace: false});
});
```

**Comment by djett41** [comment]
Cool sounds good @kasperp .  As far as the watch flag, I was thinking the watchDepth (or simply depth) would have 3 types (reference, collection, and value as noted in https://docs.angularjs.org/guide/scope )  

I would normally say it would probably be best to default this to reference, however since you are forcing the watch depth to value right now, it may make sense to keep that consistent so existing implementation code may not require a change.

Let me know your thoughts

**Comment by kasperp** [comment]
@djett41 yeah sounds good, to keep the naming consistent with angular.

I think `watchDepth` is better that `depth` as it is easier to undestand its purpose.

I agree I shouldn't break backwards compatibility so default to `value` sounds good. 

:+1: thanks again

**Comment by djett41** [comment]
@kasperp 

Just sent in a pull request.  The watchDepth feature has been implemented with the following logic

watchDepth equal to 'collection' ? $watchCollection is invoked
watchDepth equal to 'group' ? $watchGroup is invoked
watchDepth equal to 'reference' ? $watch is invoked (no deep watch)
otherwise $watch is invoked with deep watching by value (true sent in as 3rd argument)

I only modified the ngReact.js file (wasnt sure if you wanted to minify yourself in case you had other pull requests coming, or you like to own that anyway)  Also I'm not too familiar with coffee script (assuming thats what your tests are in?) so I didnt add to your test file :( but let me know if you would like me to create a separate test file just for this feature.
