### ISSUE TITLE
Using a directive inside a React component

### ISSUE THREAD

**Issue by marekkalnik** [davidchang/ngReact#49]
Hi,

I'm trying to check if it is possible to use directives inside a react component.

The naive approach (just keeping the directive in the JSX) is obviously not working. So I tried to inject the scope and compile the directive by myself, but it seems that injecting the whole scope is not possible. Do you have any idea if it is doable? If not, I think it would be nice to mention it in the documentation, as it may be an important reason to avoid using React.

**Comment by kasperp** [comment]
Hi @marekkalnik Thanks for you question. Do you mean to use an existing angular directive inside a React Component? 

`ngReact` kind of does the opposite. I think of it as taking a part of an angular view and turning it into a React view (component). You can can use existing angular injectables as described in the [README](https://github.com/davidchang/ngReact#reusing-angular-injectables). So it is possible to share code between an angular directive and a React Component, but you'll need to make the functionality you which to share available as e.g. an angular service. 

Did that answer your question, if not please let me know if I misunderstood you.

**Comment by marekkalnik** [comment]
Yes. The idea is to use React but still keep the directives like ui-sref
working. This would speed up the migration, even if it may be suboptimal on
the performance level.

If the only thing we can reuse are services it would mean that some
directives would need a bit of refactoring to be reintegrated in React.

**Comment by kasperp** [comment]
Yeah I can see that it would speed up migration if it was possible. It is as you found out not and I'm not exactly sure it could work.

**Comment by marekkalnik** [comment]
@kasperp ok, thank you very much for your anwsers. I think it should be just a bit clearer in the documentation. I'll submit à PR.

**Comment by kasperp** [comment]
yeah we could improve til docs in this regards. Thanks

**Comment by monah-abouassi** [comment]
Hi All, 
I would like to know if any changes has been made since this PR is submitted.
Thank you

**Comment by kasperp** [comment]
@monah-abouassi sorry I don't understand your question.

**Comment by monah-abouassi** [comment]
Hi 
I am sorry I didn’t clarify my question I would like to know if it s possible at least to load the html file of the directive so we do not have code duplication and the functions will be written in a different service.
Thank you

**Comment by kasperp** [comment]
okay the discussion around support directives inside components is on #120, but no nothing have been completed yet.
