### ISSUE TITLE
Sope function with return

### ISSUE THREAD

**Issue by RudmanMario** [davidchang/ngReact#51]
I'm new to ng-React and I'm trying to run function from scope in my react component and get the return value from that function. I've managed to run scope function by adding this my view:
```html
<cell get-data="getSomething"/>
```
And by making this in my react class:
```javascript
var ReactTableRow = React.createClass({
    propTypes: {
        getData: React.PropTypes.func
    },
    render: function() {
        var foo= this.props.getData(400);
        return (
            React.DOM.div(null, foo)
        )
    }
});
```

And my controller:
```javascript
$scope.getSomething = function(number) {
    return number + 10;
}
```
So, when i debug i can see that my function is being called but the return is not working. Any ideas how to make that possible?

**Comment by kasperp** [comment]
@RudmanMario thanks for you question. 

The return value from passed in functions isn't available. You generally want data to flow into React component through the `probs`. So if the data needs to be calculated based on some action, I would let that action recalculate the data "bound" to the `probs`. In your example that would be something like this:

Angular View:
```html
<cell recalc="recalc" data="data"/>
```

React Component
```javascript
var ReactTableRow = React.createClass({
    propTypes: {
        recalc: React.PropTypes.func,
        data: React.PropTypes.object
    },
   
    render: function() {
        return (
            React.DOM.div( {onClick: this._handleOnClick}, data)
        )
    },

   _handleOnClick: function() {
     this.props.recalc( 400 );
  }
});
```

Angular controller
```javascript
$scope.recalc = function(number) {
    $scope.data = number + 10;
}

$scope.data = $scop.recalc( 400 )
```

**Comment by RudmanMario** [comment]
Thank you for the response. At least now I know that it's not possible to get the return value so I can focus on trying something else. Your solution is fine, but I'm trying to avoid generating new watchers which was the reason I decided to work with react. Thanks again, I'll try some different approach for my problem.
