### ISSUE TITLE
Can this be used with ngTasty?

### ISSUE THREAD

**Issue by billfranklin** [davidchang/ngReact#52]
I like the features of the tables in ngTasty, but rendering is still pretty slow.  I'd like to know if anyone has used ngReact with the ngTasty tables...

**Comment by kasperp** [comment]
@billfranklin thanks for you question. I haven't worked with `ngTasty` but looking at their docs I'm not sure how I use `ngReact` to make it faster. Did you have any more specific thoughts ?

For speeding up larges tables I would suggest letting a react component deal with all of the table rendering as is done in the table example https://github.com/davidchang/ngReact/tree/master/examples/table
