### ISSUE TITLE
Include React Templates as ngReact directives?

### ISSUE THREAD

**Issue by alejandroiglesias** [davidchang/ngReact#53]
Hey, I'm testing this project and just found [React Templates](https://github.com/wix/react-templates) and seems there's some useful ones like rt-repeat and similarly useful stuff. I was wondering if that could be included as a part of ngReact to use as drop-in replacements for AngularJS directives, like using `rt-repeat` instead of `ng-repeat` and automatically having the benefits of React rendering.
I would contribute to that but i'm still a bit alien to this project. Let me know if you guys can help me getting started with ngReact internals so that i can contribute or you also think it's a good idea and can work on that.
Best!

**Comment by kasperp** [comment]
@alejandroiglesias it it sounds interesting, it is related to the discussion here #7 ?

**Comment by alejandroiglesias** [comment]
@kasperp yes, it *is* indeed related. And what is being thought in that discussion is great, ie, the ability to do this:
```
<react-render>
  <div ng-repeat="x in y">{{x.name}}</div>
</react-render>
```
and having React render that super-fast sounds like an awesome deal really.

**Comment by kasperp** [comment]
I'll close this then
