### ISSUE TITLE
Demo: large table memory keep going up when continuously scroll.

### ISSUE THREAD

**Issue by myc0210** [davidchang/ngReact#54]
Any one can explain me why this happens for that demo? Can this be consider kind of memory leak?

**Comment by kasperp** [comment]
@myc0210 thanks for reporting this. Could you provide some more information about the experiments you conducted ?

**Comment by myc0210** [comment]
@kasperp  Sorry. I want to reproduce the issue, but it works fine today. I think i missed checking something that time while trying the demo.
