### ISSUE TITLE
Watch expression initial value false-positive

### ISSUE THREAD

**Issue by ethul** [davidchang/ngReact#58]
I realize we just merged #57 but after using this a bit more, I've come across a case where I am getting an initial value in the watch expression that is different from the value first passed to the directive wrapping the react component.

For example:

```javascript
function FooController($q) {
  var that = this;

  this.values = [1,2,3];

  $q.when([4,5,6]).then(function(as) { that.values = as; });
}
```

```html
<div ng-controller="FooController as foo">
  <foo-react-component values="foo.values" watch-depth="reference"></foo-react-component>
</div>
```

In this case, the `FooReactComponent`'s render function will be invoked with `[1,2,3]`. And I would expect it to be then be invoked with `[4,5,6]` as a result of the watch expression on `foo.values`. However, the watch expression is initialized with `newValue === [4,5,6]` and `oldValue === [4,5,6]`, and so from #57, the render function will not be invoked (I am not sure why the `oldValue` is not `[1,2,3]`).

One way that I think this can be fixed is that we really want to compare `newValue` in the watch expression with the initial value passed in the props when the react component is first rendered. And these initial values could be stored when the `scope.$eval` is called to obtain them. I can write up a PR to illustrate this, but I am wondering if this is getting too complicated. Maybe the multiple render calls is not that big of a deal.

What are your thoughts?

**Comment by ethul** [comment]
Actually, another solution could be #56. I realize this was not perhaps ideal, but I believe it would resolve this issue. I'd have to test it out a bit further though.

**Comment by kasperp** [comment]
hmm. 

>  (I am not sure why the oldValue is not [1,2,3])

Yeah I agree that seems odd.

> .. but I am wondering if this is getting too complicated. Maybe the multiple render calls is not that big of a deal.

I'm starting to agree with this.

**Comment by ethul** [comment]
I wonder if we should revert PR #57 for the moment. I think that approach may require further investigation.

**Comment by kasperp** [comment]
yeah - lets do that - thanks for being thorough

**Comment by ethul** [comment]
Sounds good. Sorry that I did not catch this sooner. I will dig into it a bit more.

Are you able to revert the merge through the Github PR page? Or would you like me to send a separate PR to revert?
