### ISSUE TITLE
Dynamically changing rowSpan

### ISSUE THREAD

**Issue by RudmanMario** [davidchang/ngReact#60]
I have a problem when trying to update my table. This is how my initial table looks like:

![Image of initial table](http://i57.tinypic.com/2isebno.png)

So the rowspan here works fine. My **"Row"** table cell looks like this:

```javascript
<th className="rotate header" rowSpan={this.props.tableFoo.axisY.ordinates.length}><div><span>Row</span></div></th>
```
So I'm looking for the length of ordinates array for axis Y and that is the number of rows which I want my **"Row"** cell to cover. 
Then on "Add new Y ordinate" click this is fired:
```javascript
$scope.addNewYOrdinate = function() {
            $scope.tableFoo.axisY.ordinates.push({
                id: 12348,
                label: "Ordinate Y 4"
            });
};
```
The ract table re-renders because the props has changed and this is what I get in result:
![Image of final table](http://i58.tinypic.com/2hprv4y.png)

So for some reason, although the rowspan changes to 4 and I can see that when inspecting elements, the actual rowspan still remains 3. Why is that? Is it a bug?

**Comment by kasperp** [comment]
@RudmanMario that does seems strange. Because rowspan **is** updated in the DOM makes me think that this isn't a `ngReact` issue though. 

Do you see the same problem in other browsers ? 

Have you tried using your component without of angular and ngReact and does it act the same way ?

**Comment by RudmanMario** [comment]
I've checked the other browsers and it looks the same there. Rowspan is updated but it doesn't span four rows. 
I haven't tried using the component just in `React` but I guess I should, if you think it has nothing to do with `ngReact`. I'll see what how will behave and let you know.

**Comment by RudmanMario** [comment]
It looks like it is a `React` problem. I made a [fiddle](http://jsfiddle.net/zavLf6cz/2/) so you can check it yourself. Really strange behavior if I'm not making some mistake in my code.

**Comment by RudmanMario** [comment]
It officially is a `React` problem. I needed to include `<tbody>` in my `<table>`. It was that simple, but strange problem nonetheless. In the next `React` release there will be a warning about including `<tbody>` tags in `<table>`.

**Comment by kasperp** [comment]
@RudmanMario cool thanks for the update. I'll close this issue then :smile:
