### ISSUE TITLE
Trying to get react-canvas working with ngReact

### ISSUE THREAD

**Issue by oliviercooper** [davidchang/ngReact#61]
Hi,

ngReact is easy to install and to use with angularjs...
... but how to proceed when you want to use a react library like flipboard/react-canvas as it relies on requirejs.

I tried without success to load react and react-canvas with browserify.
Maybe I'm on the wrong way ?

oliver

**Comment by kasperp** [comment]
@oliviercooper thanks for reporting this.

I created this [pull request](https://github.com/thetutlage/ng-react-test/pull/1) a while back, to show how you could use browerify with ngReact. Perhaps you can find some inspiration there. 

Let me know how you get on.

**Comment by oliviercooper** [comment]
Hi,
I spent a lot of time trying to make it works without success (I think because of my project structure).

I decided to upgrade my project to a new angularjs boilerplate (https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate)
Just starting with this one, it seems to be easier.

For using ngReact I followed your pull request tips : 

'use strict';

var angular = require('angular');

// angular modules
require('angular-ui-router');
require('react');
require('ngreact/ngReact');
require('./templates');
require('./controllers/_index');
require('./services/_index');
require('./directives/_index');

// create and bootstrap application
angular.element(document).ready(function() {

  var requires = [
    'ui.router',
    'react',
    'templates',
    'app.controllers',
    'app.services',
    'app.directives'
  ];

  // mount on window for testing
  window.app = angular.module('app', requires);

  angular.module('app').constant('AppSettings', require('./constants'));

  angular.module('app').config(require('./routes'));

  angular.module('app').run(require('./on_run'));

  angular.bootstrap(document, ['app']);

});


As you seen, the only difference is require('ngreact/ngReact') and not require('ngReact') as the node_modules folder is in minus characters, why ?

oliver

**Comment by kasperp** [comment]
@oliviercooper did you figure out what the problem was ?

**Comment by oliviercooper** [comment]
hi,
My initial project was not relying on requirejs and It was too complex to properly integrate angularjs and requirejs. A good refactoring and boilerplate migration were usefull.

oliver
