### ISSUE TITLE
publish new version to npm

### ISSUE THREAD

**Issue by dlmanning** [davidchang/ngReact#65]
Looks like there've been some features added to master that aren't in the npm module. Would you mind publishing the latest? Pretty please :)

**Comment by kasperp** [comment]
@davidchang :smiley_cat:

**Comment by chino23** [comment]
@hasdavidc :)

**Comment by hasdavidc** [comment]
noted, sorry guys :/ i've been super flaky for many months now, need to sort out my commitments and priorities. this open source/responsibility thing is not as easy [for me] as @kasperp makes it out to be :P

**Comment by chino23** [comment]
Hey @hasdavidc, no worries, we understand that :) And just to be clear, we all hugely (!) appreciate your effort here. It's awesome!

**Comment by hasdavidc** [comment]
High five, 0.1.5 is out:

https://www.npmjs.com/package/ngreact
https://github.com/davidchang/ngReact/releases/tag/0.1.5

Closing.

**Comment by chino23** [comment]
Thanks David!

**Comment by kasperp** [comment]
:+1:

**Comment by dlmanning** [comment]
thanks!
