### ISSUE TITLE
Controller <-> Directive communication

### ISSUE THREAD

**Issue by zzarcon** [davidchang/ngReact#66]
Hi guys I'm trying to modify the value of an angular controller from the angular directive; so lets suppose I have this code:

**Application**
```javascript
var fooComponent = React.createClass({
  getInitialState: function() {
    return {
      foo: this.props.foo
    };
  },

  handleChange: function(e) {
    this.setState({foo: e.target.value});
  },

  render: function() {
    return (
      <input type="text" value={this.state.foo} onChange={this.handleChange}/>
    );
  }
});

app = angular.module('app', ['react']).controller('helloController', function($scope) {
    $scope.componentProps = {foo: "bar"};
});

app.value('fooComponent', fooComponent);
```

**Hello Template**
```html
<body ng-app="app">
  <div ng-controller="helloController">
    {{componentProps.foo}}
    <react-component name="fooComponent" props="componentProps" watch-depth="reference"/>
  </div>
</body>
```

What I want it's whenever the **fooComponent** changes their state, the angular controller notice that change and render their value.

Do you think that this it's possible guys? In case of not, can you tell me why not, and what are the alternatives?

Thanks you much for the lib, looking forward to your answer :)

**Comment by kasperp** [comment]
@zzarcon thanks for you question. State change from a react component "back" to the angular controllers must go through callbacks. See this [comment](https://github.com/davidchang/ngReact/pull/11#issuecomment-60485903) that also include and example of how to do so.

**Comment by zzarcon** [comment]
@kasperp Thanks for fast answer, I just used your approach and it works :+1:. 

So, what I see is that you don't want to do something like `$scope.$apply` every time that the state of the React component change and get the Angular template up to date, because you think that it's not responsibility of **ngReact**, right? (or maybe I'm wrong and that will be a great feature for this directive) :)

**Comment by kasperp** [comment]
@zzarcon glad that it worked for you.
