### ISSUE TITLE
Possible Performance Boost

### ISSUE THREAD

**Issue by brigand** [davidchang/ngReact#7]
I don't know all of the low level stuff in angular, but looking at ngReactRepeat there might be a way to optimize it.

If you can take the nodes that would be transcluded, and instead generate a simple tree of them, along with an array of keys to watch when the directive is compiled, you could use that in the component's render for more efficiency.  

If you could get it to the point where e.g. the html is retrieved at compile time, transclusion doesn't happen, and that can be made available to the reactUnit::render as props, I can do the rest.

**Comment by lylepratt** [comment]
I came here to see if anyone was doing this yet. I think its a great idea. Has any progress been made?

**Comment by djett41** [comment]
I would love to see this as well.  Would be happy to contribute if you guys steer me along the path you were thinking.  Or even implement one of the attributes such as ng-class.. Would be happy to help tackle some of the others

**Comment by kasperp** [comment]
@lylepratt, @djett41 sorry for the late response. I don't believe there has been any progress made on this idea yet. 

I think it is an interesting idea. For transitioning angular apps to react app would it also be useful if other react components could be used inside `react-render` ? like

```html
<react-render>
  <div>hey {{someAngularExpression}}</div>
  <div ng-class="..." ng-repeat="x in xs">
    <component x={x}/>
  </div>
</react-render>
```


@davidchang have you given this any more thought ?

**Comment by thomasquintana** [comment]
I'm also interested in this idea since using the ReactJS virtual DOM will greatly speedup ng-repeat. If there is anyway I can help please let me know.

**Comment by alejandroiglesias** [comment]
Those snippets look awesome. I need to "port" an Angular template into React for performance and the main pain-points seem to be replacing `ngRepeat`, `ngIf`, `ngShow`/`ngHide` and `ngClass`. Having the ability to wrap all the template into `<react-render>` tags and getting React performance auto-magically sounds exciting and very promising! Would be happy to make small contributions as time permits.

**Comment by brigand** [comment]
Does anyone know how to intercept angular's processing of a directive's children?  That's what's blocking here; I need the dom untouched.

**Comment by robinboehm** [comment]
@brigand are you searching for `terminal` on $compile service?

https://docs.angularjs.org/api/ng/service/$compile

**Comment by lylepratt** [comment]
I think the approach to accomplishing this should be very similar to how the Famo.us Angular integration works. Links to Famo.us surfaces implemented as Angular directives:
https://github.com/Famous/famous-angular/tree/master/src/scripts/directives

**Comment by kasperp** [comment]
I was thinking about closing this issue, as:

* The discussion seems to have gotten stale
* What is being discussed here (although interesting) seems to be outside of what ngReact is

Any strong opinions before I do so ?
