### ISSUE TITLE
Protractor / E2E - How to address ngReact components?

### ISSUE THREAD

**Issue by lourenzo** [davidchang/ngReact#70]
Hello,
I've been working on a project with ngReact glueing angular, React and some more together.

A new challenge I've faced now is how is a good practice to address React Component display / input fields when writing the specs.

May I have your advice?

Regards,
Lourenzo Ferreira

**Comment by kasperp** [comment]
@lourenzo I haven't done any E2E with ngReact, so I wouldn't know what to advise ? I have written unit tests for components using karma that was fairly straight forward. 

Have you any experience setting up E2E tests you can share or any concrete issues ?

**Comment by lourenzo** [comment]
@kasperp , actually I decided to move out AngularJS and use react-router and reflux, and the QA team is creating the E2E tests with Selenium.
But I appreciate the help and the gateway that ngReact created to me, from Angular to React + *Flux

**Comment by kasperp** [comment]
nice
