### ISSUE TITLE
Include react main.js file as-is?

### ISSUE THREAD

**Issue by OKNoah** [davidchang/ngReact#75]
I've created a simple react component and included the `main.js` script in my `index.html`. It uses Browserify. When I try use it on the page in the native React way (`React.render( component, document.querySelector( '.put-it-here')`), it can be replaced in the DOM when Angular refreshes a state. That's what brought me here. 

Is there a way to keep this `main.js` file as-is and create a directive from it? I'm getting errors that my components are undefined right now.

None of the examples seem to include another outside file for React code.

I hope this makes sense, I'm new to React.

**Comment by kasperp** [comment]
@OKNoah thanks for you question. 

React Components can be "exposed" to ngReact in two ways. Either on the global object like `window.MyComponent = MyComponent` or with angular dependency injection as shown in the [README](https://github.com/davidchang/ngReact#the-react-component-directive)

Did that answer your question ?

**Comment by OKNoah** [comment]
I'll share how I got this working.

First, my main file, `app.jsx`, _was_ something like this (_berfore_ I got it working):

	var React = require( 'react' ),
		SidebarComponent = require( './sidebar-component' )

	var sidebar = React.createElement( SidebarComponent, {
		prop1: "value",
		prop2: "value"
	} )

	module.exports = sidebar

Obviously I could not access `sidebar` in Angular no matter what I did. So I took the contents of `sidebar-component.js` and put that in `app.jsx` instead:

	var React = require( 'react' ),
		LogoButton = require( './logo-button' ),
		Sidebar = require( './sidebar' )

	var SidebarComponent = React.createClass({
		handleClick: function () {
			/*Stuff here*/
		},
		getInitialState: function () {
		    return {
		    	/*Stuff here*/
		    }
		},
		render: function () {
			return 	/*JSX stuff here*/
				<LogoButton ... />
				<Sidebar ... />
		}
	})

	app.value( 'SidebarComponent', SidebarComponent )

Then, I made sure I included Angular before including the compiled `app.jsx` (which I called `main.js`):

	<script src="vendor/ngReact/ngReact.js"></script>
	<script src="app/app.js"></script>
	<script src="app/controllers/HomeController.js"></script>
	<script src="js/main.js"></script>

In `app.js`, my main Angular file, I put this:

	app.directive( 'sidebarButton', [ 'reactDirective', function ( reactDirective ) {
		return reactDirective( 'sidebarComponent' )
	}])

In my `HomeController` file, I put the props as part of an object:

	$scope.sidebarProps = {
		prop1: "value",
		prop2: "value"
	}

Finally, I just included this in the HTML within the HomeController scope:

	<react-component name="SidebarComponent" props="sidebarProps" watch-depth="reference" />

I think the major stumbling block was including the React class, not the React element. But I also did a lot of trial and error along the way.

Thanks @kasperp for the response. Hopefully the above helps someone too.
