### ISSUE TITLE
Callback losing scope.$apply() wrapper after another prop changes

### ISSUE THREAD

**Issue by psalaets** [davidchang/ngReact#78]
I'm using the `react-component` directive with `props` set to something like

```js
{
  clicked: function() {
    $scope.count += 1;
  },
  name: 'blah'
}
```

The React component calls `this.props.clicked` when it is clicked. If I change another prop (e.g. `name` in the above snippet) on the angular side then it seems as if `clicked` is no longer called in a `scope.$apply()` block.

I didn't explain this very well, but here is a plunker demonstrating the issue: http://plnkr.co/edit/pbps2zuUmcrCrrsY2rU1?p=preview

Am I doing something wrong here?

**Comment by psalaets** [comment]
When a prop changes, the component is re-rendered and any functions in props are wrapped in `scope.$apply()` -- [line ~150](https://github.com/davidchang/ngReact/blob/master/ngReact.js#L150).

Because of `wrappedInApply` added to functions on [line 61](https://github.com/davidchang/ngReact/blob/master/ngReact.js#L60), callbacks won't be wrapped again but it seems like they should be wrapped every single time.

**Comment by kasperp** [comment]
@psalaets thanks for reporting this and providing a running example that fails. I'll look into the problem. 

In the mean time you can move the data that you bind to in angular outside of the data that you transfer to React. I updated you plunker to show this http://plnkr.co/edit/iKb2cvER81JlGFcIs7Uq?p=preview

**Comment by psalaets** [comment]
I've got failing tests for this in a fork, I could submit them via PR or something.

Thanks for the workaround, I think that should work for me.

**Comment by kasperp** [comment]
>I've got failing tests for this in a fork, I could submit them via PR or something.

PR would be very helpful - thanks

**Comment by psalaets** [comment]
PR sent as #79

**Comment by javiercr** [comment]
Thank you for reporting this, I was having the exact same problem and I thought I was doing something wrong :D

**Comment by kasperp** [comment]
Hi guys, thanks for your feedback. 

I created pull request #81. It now passes the tests that @psalaets wrote. Let me know if it solves the issue for you.

**Comment by psalaets** [comment]
Yep it's resolved now. I updated the plunker example, which is also working: http://plnkr.co/edit/115ZeTD6KXdGEnkwchWp?p=preview

Thanks for the quick turnaround on this.
