### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'deepestAncestor.firstChild')

### ISSUE THREAD

**Issue by OKNoah** [davidchang/ngReact#82]
I get this error in the console on any `onChange` event when using `react-inline-edit` component. But I don't get it when I use it without `ng-react`.

I also made an issue here with more details: https://github.com/vasanthk/React-InlineEdit/issues/3

**Comment by kasperp** [comment]
@OKNoah thanks for reporting this. If you could provider some kind of running example in plunker or jsfiddle, It would be appreciated.

**Comment by kasperp** [comment]
@OKNoah is this still a problem or did you solve it?

**Comment by kasperp** [comment]
closed due to inactivity.
