### ISSUE TITLE
passed function does not return any value

### ISSUE THREAD

**Issue by oriweingart** [davidchang/ngReact#85]
When passing a function to react component the service wraps it by  $scope.$apply which doesn't return a value.
example:
in controller:

```javascript
$scope.addHello = function(name){
                var newName = "Hellow "+name;
                console.log("New name in NG controller:",newName);
                return newName;
            }
$scope.data = {addHello : $scope.addHello};
````

In react JSX file:

```javascript
var Hello = React.createClass({
    render: function() {
        var newName = this.props.addHello("World");
        console.log("New name in ngReact:",newName);
        return (<div>
                    {newName}
                </div>)
    }
});

app.directive( 'hello',  function( reactDirective) {
    return reactDirective( Hello );
});
```

In HTML:
```html
<react-component name="Hello" props="data" />
```

Result in console:

```
New name in NG controller: Hellow World
New name in ngReact: undefined
````

Result in html after render:

```html
<react-component name="Hello" props="data">
       <div data-reactid=".2"></div>
</react-component>
```

**Comment by oriweingart** [comment]
https://github.com/davidchang/ngReact/pull/86 solve this issue

**Comment by kasperp** [comment]
@oriweingart you're right that the wrapped function doesn't return. 

To get data from angular into react you pass in props with that data. If you want to run some kind of transform function on that data before rendering. I would suggest using either just a regular function or an angular filter as shown here https://github.com/davidchang/ngReact/blob/master/examples/use-filter/app.js 

To use a regular function, make it available to the react component (e.g. as an angular service), see https://github.com/davidchang/ngReact/issues/62#issuecomment-95698133

```javascript
// somewhere 
function sayHello(name){
   return "Hello " + name;
}

// in controller
$scope.data = {changeName : $scope.changeName, name:  };

// in react component
var Hello = React.createClass({
    render: function() {
        return (<div>{sayHello(this.props.name)}</div>)
    }
});
```

**Comment by oriweingart** [comment]
yes but in many cases I don't want to wrap the entire code by app.factory, there for I do need to inject functions and get their return value.

**Comment by kasperp** [comment]
What if you defined those functions together with the React components.

```javascript
function addHello( name ) { ... }

var Hello = React.createClass({
    render: function() {
        var newName = addHello("World");
        return (<div>{newName}</div>)
    }
});
```

or in if you have multiple put them in an object. 

```javascript
var mylib = {
  addHello: function( name ) { ... }
  ,...
}

var Hello = React.createClass({
    render: function() {
        var newName = mylib.addHello("World");
        return (<div>{newName}</div>)
    }
});
```

**Comment by oriweingart** [comment]
Hi, in my case those are global functions which are defined in my angular app and shared by many controllers and services.. I don't want to duplicate it in React.
Please check PR: https://github.com/davidchang/ngReact/pull/86 which solved this issue easily

**Comment by kasperp** [comment]
Thanks for the PR, I did see that :smile:, and I'm sorry but I'm not convinced why this a good idea. If you have the functions as globals, why don't you just call them from the React Component ?

I guess I don't fully understand your use-case could you elaborate a little on that ?

**Comment by targumon** [comment]
A habit I acquired back in my jQuery days is that *every* JS function should have a return statement.

So I'm totally with @oriweingart on this one. And a very strong point in his favor is that the PR he suggests has no downsides as far as I can see because existing code will continue to work - in other words, oriweingart and anyone with a similar use case wins, nobody else loses.

**Comment by chaim-aharonson** [comment]
I agree with @targumon and @oriweingart, I run into similar issue and had to use vanilla JS in order to solve - it'd better be the Angular way or in other words - @oriweingart way with adding this small patch to the React amazing code.

**Comment by hasdavidc** [comment]
I agree with @kasperp that the use case mentioned in this ticket is not exactly sufficiently compelling, and that if the desired functions are globals, they should be just utilized directly from the React component (that'd potentially be better than passing down props unnecessarily).

At the same time, I agree with @targumon that adding returns here doesn't have any downsides or cause any legitimate danger. For that reason, I'm going to go ahead and merge #86, I hope you don't mind @kasperp :/

**Comment by hasdavidc** [comment]
Closing as #86 was merged, this has been released in version 0.1.7

**Comment by kasperp** [comment]
No it is fine. It seems like a popular request and as you mentioned it doesn't do any harm. 

I think reading the first example where a function on the scope (which potentially modifies the scope and thereby the props) is called inside render spooked me a little. 

Anyway it would be nice with a test for this as well.

**Comment by oriweingart** [comment]
PR https://github.com/davidchang/ngReact/pull/91 has a new test case for verifying the return value within the React class.
