### ISSUE TITLE
How to make watch-depth in ngReact work

### ISSUE THREAD

**Issue by yccheok** [davidchang/ngReact#89]
By using `watch-depth`, I expect React component will re-render itself, when AngularJS's scope data is changing.

My code looks like this

index.html
----------

    
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello React</title>
        <script src="bower_components/angular/angular.js"></script>
        <script src="bower_components/react/react.js"></script>
        <script src="bower_components/jquery/dist/jquery.min.js"></script>
        <script src="bower_components/ngReact/ngReact.min.js"></script>
        <script src="build/commentbox.js"></script>
    </head>
    <body>
    
    <script>
        var app = angular.module('myApp', ['react']);
        app.controller('myCtrl', function($scope) {
            $scope.firstName= "John";
            $scope.lastName= "Doe";
    
            setTimeout(function() { 
                alert('assign data! how to trigger react component?');
                $scope.data = {data : [
                    {author: "Pete Hunt", text: "This is one comment"},
                    {author: "Jordan Walke", text: "This is *another* comment"}
                ]};       
            }, 5000);
        });
        app.value('CommentBox', CommentBox);
    </script>
    
    <div ng-app="myApp" ng-controller="myCtrl">
        First Name: <input type="text" ng-model="firstName"><br>
        Last Name: <input type="text" ng-model="lastName"><br>
        <br>
        Full Name: {{firstName + " " + lastName}}
        <react-component name="CommentBox" props="data" watch-depth="reference"/>
    </div>
    
    </body>
    </html>

commentbox.js
-------------

    // tutorial4.js
    var Comment = React.createClass({
      render: function() {
        return (
          <div className="comment">
            <h2 className="commentAuthor">
              {this.props.author}
            </h2>
            {this.props.children}
          </div>
        );
      }
    });
    
    // tutorial10.js
    var CommentList = React.createClass({
      render: function() {
        console.log("DEBUG");
        console.log(this.props);
        var commentNodes = this.props.data.map(function (comment) {
          return (
            <Comment author={comment.author}>
              {comment.text}
            </Comment>
          );
        });
        return (
          <div className="commentList">
            {commentNodes}
          </div>
        );
      }
    });
    
    // tutorial1.js
    var CommentBox = React.createClass({
      render: function() {
    
    
        return (
          <div className="commentBox">
            <h1>Comments</h1>
            <CommentList data={this.props.data} />
          </div>
        );
      }
    });

There's no difference, whether I'm using `watch-depth="reference"` or `watch-depth="value"`. `React` component won't render itself, when value is assigned to `$scope.data`

Is there anything I had missed out?

p/s Cross post at http://stackoverflow.com/questions/31262434/how-to-make-watch-depth-in-ngreact-work

**Comment by hasdavidc** [comment]
@yccheok I just took a rudimentary look, hope I'm not missing something bigger, but did you try this before without the timeout? $timeout would be necessary to trigger another digest cycle, which should theoretically then trigger the React re-render.

Could you verify whether this works with $timeout instead of setTimeout?

**Comment by yccheok** [comment]
Without timeout, it works fine as $scope data filled with complete data,
before react component tries to render itself.

**Comment by yccheok** [comment]
As side note, I'm using 

angular "version": "1.3.16"
react version": "0.13.3",
ngReact "version": "0.1.5",

**Comment by hasdavidc** [comment]
Does this work with usage of $timeout instead of setTimeout?

**Comment by yccheok** [comment]
Yes. $timeout does work. May I know why $timeout is working but not setTimeout. As the user ngReact, I expect both $timeout and setTimeout should work, as long as there's data change in $scope.data

The reason I'm using setTimeout, as I want to mimic a common case scenario : Most of the time, after react component is renderered to screen, the data model is not ready yet. 

We may need to wait ~10 seconds, to complete data model request from network API. Hence, we are using setTimeout to mimic such behavior.

**Comment by hasdavidc** [comment]
Ahh, okay. Awesome.

Yes, so this is an "issue"/misunderstanding not with ngReact, but with Angular itself. Angular itself does not know if values on the scope have changed until a digest cycle occurs.

$timeout works because it hooks into the Angular lifecycle and triggers a digest cycle once it ends. setTimeout does not work because Angular has no idea that its values have changed. (The same applies for using Angular's $http over a non-Angular aware XHR technique.)

Does that make sense? I'm going to close this issue as this is not an issue related to ngReact.
