### ISSUE TITLE
Documentation and examples are not complete

### ISSUE THREAD

**Issue by ittayd** [davidchang/ngReact#90]
The documentation and examples leave several questions open:
1. If a react component renders a directive ('<my-cell ...>'), will that work? 
2. If the above works, can the nested directive use react again?
3. If the above works, will there be a performance improvement? E.g. I render a table where all <tr> are rendered with a directive (and even all <td>). These directives use react, but since it is not one big template, but many small ones, will there be a performance boost?

**Comment by kasperp** [comment]
@ittayd thanks for you issue, you are welcome to open a pull request with suggestions to the documentation. 

But to answer your question: 

> 1. If a react component renders a directive (''), will that work? 

No you cannot use a directive from within a react component, see #49
