### ISSUE TITLE
TypeError: Cannot read property '_currentElement' of null

### ISSUE THREAD

**Issue by yordis** [davidchang/ngReact#96]
I am just trying to create some component who render Griddle and I get this

**Comment by hasdavidc** [comment]
could you provide more code for us to be able to diagnose what's happening?

**Comment by yordis** [comment]
@hasdavidc so far is Griddle the problem, for some reason doesn't render. The component works outside of Angular environment :( 

```js
import React from 'react'
import Griddle from 'griddle'

export default
class List extends React.Component {
  static defaultProps = {
    data: []
  }

  constructor(props) {
    super(props)
  }

  render() {

    return (
      <Griddle
               results={this.props.data}
               />
    )
  }
}

```

**Comment by hasdavidc** [comment]
Could you double check that you're using the proper version of React and only loading it once? This error seems like it is not specific to Griddle or ngReact: https://github.com/JedWatson/react-select/issues/128#issuecomment-103119668

**Comment by yordis** [comment]
@hasdavidc thank you very much. I didn't realize I had two reacts, one in the bundle and the other one from the gem. My bad.

The Problem: Loading React twice.

**Comment by hasdavidc** [comment]
:D Glad I could help!
