### ISSUE TITLE
Cannot find react component

### ISSUE THREAD

**Issue by chrillewoodz** [davidchang/ngReact#97]
I've been trying to get this to work for ages, but no matter what I do the directive can't find my react component. 

These are the files I'm including:

    <script src="bower_components/react/JSXTransformer.js"></script>
    <script src="bower_components/react/react-with-addons.js"></script>
    <script src="bower_components/ngReact/ngReact.min.js"></script>
    <script src="node_modules/babel-core/browser.js"></script>
    <script src="static/react-components.min.js" type="text/babel"></script>
    <script src="static/main.min.js"></script>

Where my components are inside the react-components.min.js file, and all of my angular code is inside main.min.js. 

It's stated that you need to use an in browser transformator for this directive to work, so I tried that using babel, but that also doesn't work. 

This is my react component:

    <react-component name="Chat" watch-depth="reference"></react-component>

And in the react-components.min.js file I got a component called 'Chat':

    var Chat = React.createClass({
       render: function() {
        return <footer className="chat chat--dark">Hello John</footer>;
      }
    });

core.value('Chat', Chat); // My application is bound to the core module

But it doesn't find it.. What could be wrong because no one else seems to have this issue?

**Comment by kasperp** [comment]
@chrillewoodz I see that you put the JSXTransformer.js in your scripts and that your component is written with JSX. Have you checked out the section about [JSX in the browser](https://github.com/davidchang/ngReact#jsx-transformation-in-the-browser) from the README.md ?

**Comment by chrillewoodz** [comment]
@kasperp Yes, that's why I tried using babel to fix the issue. So I removed type="text/jsx" and used type="text/babel" instead, so then it should be working but it's not.

**Comment by kasperp** [comment]
> It's stated that you need to use an in browser transformator for this directive to work, so I tried that using babel, but that also doesn't work.

This is not true, it is stated that if you want to use an in browser jsxtransformer you can. Have you tried tranforming your jsx file, in a build step? Either with [Babel](https://babeljs.io/docs/usage/jsx/) or [react-tools](https://www.npmjs.com/package/react-tools) ?
